<?php $this->load->view('/front/header'); ?>
<div class="container pt-4 pb-4">
        <h3 class="pb-3">About Institute</h3>
        <p class="text-muted text-justify">Welcome to Student Management system.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consectetur, dolor. Perspiciatis sapiente recusandae quibusdam velit, fugit expedita tenetur quidem ipsa molestias. Atque ut eos magni impedit saepe consequatur? Nostrum, quisquam.</p>
        <p class="text-muted text-justify">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Error soluta sed officiis cupiditate odit facere voluptates recusandae minima provident, ab perspiciatis tempora sint molestias cum excepturi temporibus animi, earum ullam architecto tempore aut quod, nostrum ad. Blanditiis suscipit voluptate fuga labore, autem ad ex vitae earum magnam ipsa harum cupiditate soluta dicta fugiat doloremque quae. Repellat alias iure perferendis deserunt ducimus, sint consectetur iusto error voluptas similique autem eveniet, officiis beatae modi asperiores dicta ab? Iste consequuntur officia labore sint, repudiandae, aut porro fuga praesentium qui architecto odio eveniet nostrum eos ab ex assumenda deleniti dolorum est atque sunt sit.</p>
        <p class="text-muted text-justify">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Error soluta sed officiis cupiditate odit facere voluptates recusandae minima provident, ab perspiciatis tempora sint molestias cum excepturi temporibus animi, earum ullam architecto tempore aut quod, nostrum ad. Blanditiis suscipit voluptate fuga labore, autem ad ex vitae earum magnam ipsa harum cupiditate soluta dicta fugiat doloremque quae. Repellat alias iure perferendis deserunt ducimus, sint consectetur iusto error voluptas similique autem eveniet, officiis beatae modi asperiores dicta ab? Iste consequuntur officia labore sint, repudiandae, aut porro fuga praesentium qui architecto odio eveniet nostrum eos ab ex assumenda deleniti dolorum est atque sunt sit.</p>
        <p class="text-muted text-justify">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Error soluta sed officiis cupiditate odit facere voluptates recusandae minima provident, ab perspiciatis tempora sint molestias cum excepturi temporibus animi, earum ullam architecto tempore aut quod, nostrum ad. Blanditiis suscipit voluptate fuga labore, autem ad ex vitae earum magnam ipsa harum cupiditate soluta dicta fugiat doloremque quae. Repellat alias iure perferendis deserunt ducimus, sint consectetur iusto error voluptas similique autem eveniet, officiis beatae modi asperiores dicta ab? Iste consequuntur officia labore sint, repudiandae, aut porro fuga praesentium qui architecto odio eveniet nostrum eos ab ex assumenda deleniti dolorum est atque sunt sit.</p>

</div>
<?php $this->load->view('/front/footer'); ?>
